### ISSUE TITLE
为什么我的没法创建window/mac项目呢

### ISSUE THREAD

**Issue by qssq** [LuckyLi706/flutter_mobile_command_tools#3]
我新建项目是灰色的呢。只能选择ios android web

**Comment by LuckyLi706** [comment]
flutter config --enable-linux-desktop    
flutter config --enable-macos-desktop
flutter config --enable-windows-desktop
执行这三个命令。让flutter支持桌面端。

**Comment by qssq** [comment]
大佬，有编译好的吗？我测试一下window版本的安全性。。

**Comment by qssq** [comment]
识别不了设备

**Comment by qssq** [comment]
下载你们编译的程序识别不了设备 adb路径是对的

**Comment by qssq** [comment]
额，是手动获取的

**Comment by qssq** [comment]
```
lib/main.dart(2519,41): error GC9768DF9: Undefined name 'WhitelistingTextInputFormatter'. [C:\project_github\flutter\flutter_mobile_command_tools\build\windows\flutter\flutter_assemble.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(242,5): error MSB8066: “C:\project_github\flutter\flutter_mobile_command_tools\build\windows\CMakeFiles\d391b576c98048bac5c8c8af666f222b\flutter_windows.dll.rule;C:\project_github\flutter\flutter_mobile_command_tools\build\windows\CMakeFiles\527cf84bcd24ebf587b2185833367c50\flutter_assemble.rule;C:\project_github\flutter\flutter_mobile_command_tools\windows\flutter\CMakeLists.txt”的自定义生成已退出，代码为 1。 [C:\project_github\flutter\flutter_mobile_command_tools\build\windows\flutter\flutter_assemble.vcxproj]
Exception: Build process failed.


```

是你的版本太低还是我这个flutter太高额。

**Comment by LuckyLi706** [comment]
Flutter 2.5.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 3595343e20 (8 weeks ago) • 2021-09-30 12:58:18 -0700
Engine • revision 6ac856380f
Tools • Dart 2.14.3

**Comment by LuckyLi706** [comment]
看看我的版本号。

**Comment by qssq** [comment]
我这个错误到底是什么问题呢。。就这输入的类找不到

**Comment by qssq** [comment]
```

[√] Flutter (Channel master, 2.6.0-12.0.pre.837, on Microsoft Windows [Version 10.0.19042.1288], locale zh-CN)
    • Flutter version 2.6.0-12.0.pre.837 at C:\sdk\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 341e771b12 (5 hours ago), 2021-11-24 19:33:04 -0500
    • Engine revision e99aba6a38
    • Dart version 2.16.0 (build 2.16.0-46.0.dev)
    • DevTools version 2.8.0
    • Flutter download mirror https://storage.flutter-io.cn

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\sdk\Android
    • Platform android-31, build-tools 31.0.0
    • ANDROID_SDK_ROOT = C:\sdk\Android
    • Java binary at: C:\soft\android-studio2021.1.1.12\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Professional 2022 17.0.0)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Professional
    • Visual Studio Professional 2022 version 17.0.31903.59
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] Android Studio (version 2021.1)
    • Android Studio at C:\soft\android-studio2021.1.1.12
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at C:\soft\ideaIC-2020.3.1.win
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] IntelliJ IDEA Community Edition (version 2021.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.2.1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.62.3)
    • VS Code at C:\Users\qssq5\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.28.0

[√] Connected device (4 available)
    • P8100 (mobile)    • 1cf590cf • android-arm64  • Android 9 (API 28)
    • Windows (desktop) • windows  • windows-x64    • Microsoft Windows [Version 10.0.19042.1288]
    • Chrome (web)      • chrome   • web-javascript • Google Chrome 96.0.4664.45
    • Edge (web)        • edge     • web-javascript • Microsoft Edge 96.0.1054.29

• No issues found!



```

**Comment by LuckyLi706** [comment]
> ```
> 
> [√] Flutter (Channel master, 2.6.0-12.0.pre.837, on Microsoft Windows [Version 10.0.19042.1288], locale zh-CN)
>     • Flutter version 2.6.0-12.0.pre.837 at C:\sdk\flutter
>     • Upstream repository https://github.com/flutter/flutter.git
>     • Framework revision 341e771b12 (5 hours ago), 2021-11-24 19:33:04 -0500
>     • Engine revision e99aba6a38
>     • Dart version 2.16.0 (build 2.16.0-46.0.dev)
>     • DevTools version 2.8.0
>     • Flutter download mirror https://storage.flutter-io.cn
> 
> [√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
>     • Android SDK at C:\sdk\Android
>     • Platform android-31, build-tools 31.0.0
>     • ANDROID_SDK_ROOT = C:\sdk\Android
>     • Java binary at: C:\soft\android-studio2021.1.1.12\jre\bin\java
>     • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
>     • All Android licenses accepted.
> 
> [√] Chrome - develop for the web
>     • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe
> 
> [√] Visual Studio - develop for Windows (Visual Studio Professional 2022 17.0.0)
>     • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Professional
>     • Visual Studio Professional 2022 version 17.0.31903.59
>     • Windows 10 SDK version 10.0.19041.0
> 
> [√] Android Studio (version 2020.3)
>     • Android Studio at C:\Android\Android Studio
>     • Flutter plugin can be installed from:
>        https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>        https://plugins.jetbrains.com/plugin/6351-dart
>     • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
> 
> [√] Android Studio (version 2021.1)
>     • Android Studio at C:\soft\android-studio2021.1.1.12
>     • Flutter plugin can be installed from:
>        https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>        https://plugins.jetbrains.com/plugin/6351-dart
>     • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
> 
> [√] IntelliJ IDEA Community Edition (version 2020.3)
>     • IntelliJ at C:\soft\ideaIC-2020.3.1.win
>     • Flutter plugin can be installed from:
>        https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>        https://plugins.jetbrains.com/plugin/6351-dart
> 
> [√] IntelliJ IDEA Community Edition (version 2021.2)
>     • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.2.1
>     • Flutter plugin can be installed from:
>        https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>        https://plugins.jetbrains.com/plugin/6351-dart
> 
> [√] VS Code (version 1.62.3)
>     • VS Code at C:\Users\qssq5\AppData\Local\Programs\Microsoft VS Code
>     • Flutter extension version 3.28.0
> 
> [√] Connected device (4 available)
>     • P8100 (mobile)    • 1cf590cf • android-arm64  • Android 9 (API 28)
>     • Windows (desktop) • windows  • windows-x64    • Microsoft Windows [Version 10.0.19042.1288]
>     • Chrome (web)      • chrome   • web-javascript • Google Chrome 96.0.4664.45
>     • Edge (web)        • edge     • web-javascript • Microsoft Edge 96.0.1054.29
> 
> • No issues found!
> ```

重新拉一下代码，应该是我用了一个flutter的过时方法。高版本可能移除了。已经更新了。

**Comment by qssq** [comment]
我网上下载的项目基本上各种报错，但是我不知道怎么看api文档来修复这个问题，。大佬是如何快速找到替代的方法的。

**Comment by qssq** [comment]
adb命令的读取可以基于 where  which ,和android_home变量优化下呢。

**Comment by LuckyLi706** [comment]
一般过时方法IDE会提示，where和which指的是Linux命令？android_home没有必要。我内置了一个adb，还有一个默认安装的SDK目录，你也可以手动选择。因为还有mac和linux。

**Comment by qssq** [comment]
意思是只能判断，不需要填写了。
C:\Users\qssq5>where adb
C:\sdk\Android\platform-tools\adb.exe

C:\Users\qssq5>a

**Comment by qssq** [comment]
哦哦这样啊 内置了。 我的 没提示直接报错，我用的android studio .

**Comment by LuckyLi706** [comment]
你加我微信吧，LuckyLi706。互相学习。

**Comment by qssq** [comment]
谢谢大佬
