### ISSUE TITLE
mac 桌面编译， 项目无法跑起，也无法编译

### ISSUE THREAD

**Issue by ff-frida** [LuckyLi706/flutter_mobile_command_tools#5]
as初始化完成之后，选择mac desktop，run。

➜  flutter_mobile_command_tools git:(master) ✗ flutter build macos

💪 Building with sound null safety 💪

Podfile missing
➜  flutter_mobile_command_tools git:(master) ✗ 

或者命令行直接构建，缺少podfile，是上传的时候忘记把文件上传了吗，大佬。

**Comment by LuckyLi706** [comment]
在工程下面先执行flutter packages get。

**Comment by ff-frida** [comment]
> 在工程下面先执行flutter packages get。

已经执行这个，跑项目还是这个错误

**Comment by LuckyLi706** [comment]
你用的flutter啥版本？或者你自己先创建个flutter项目，看看能不能运行macos的桌面应用。

**Comment by ff-frida** [comment]
> 你用的flutter啥版本？或者你自己先创建个flutter项目，看看能不能运行macos的桌面应用。

目前是最新3.x版本，我先试试这个【能不能运行macos的桌面应用】
